package com.licofast.api;
import org.springframework.http.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.jdbc.core.*;import org.springframework.web.bind.annotation.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;import javax.crypto.SecretKeyFactory;import javax.crypto.spec.PBEKeySpec;
@RestController @RequestMapping("/api") @CrossOrigin(origins="*")
public class ApiController {
 private final JdbcTemplate db; public ApiController(JdbcTemplate db){this.db=db;}
 @GetMapping("/health") Map<String,Object> health(){return Map.of("ok",true,"backend","java");}
 private ResponseEntity<?> error(String s,HttpStatus h){return ResponseEntity.status(h).body(Map.of("error",s));}
 private Map<String,Object> user(String token){try{String[] p=token.replace("Bearer ","").split("\\|",2);if(p.length!=2)return null;return Map.of("id",Integer.parseInt(p[0]),"rol",p[1]);}catch(Exception e){return null;}}
 private ResponseEntity<?> role(String token,String... roles){var u=user(token);if(u==null)return error("Token requerido",HttpStatus.UNAUTHORIZED);if(Arrays.stream(roles).noneMatch(r->r.equals(u.get("rol"))))return error("Acceso denegado",HttpStatus.FORBIDDEN);return null;}
 private String hash(String pass,String salt){try{byte[] b=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(new PBEKeySpec(pass.toCharArray(),Base64.getDecoder().decode(salt),120000,256)).getEncoded();return Base64.getEncoder().encodeToString(b);}catch(Exception e){throw new RuntimeException(e);}}
 private String makePass(String pass){byte[] salt=new byte[16];new SecureRandom().nextBytes(salt);String s=Base64.getEncoder().encodeToString(salt);return "PBKDF2-SHA256$120000$"+s+"$"+hash(pass,s);}
 private boolean verify(String pass,String stored){try{String[] a=stored.split("\\$");if(a.length!=4||!a[0].equals("PBKDF2-SHA256"))return false;return MessageDigest.isEqual(Base64.getDecoder().decode(a[3]),Base64.getDecoder().decode(hash(pass,a[2])));}catch(Exception e){return false;}}
 @PostMapping("/login") ResponseEntity<?> login(@RequestBody Map<String,Object> d){var rows=db.queryForList("SELECT id,nombre,apellido,usuario,password,rol,activo,edad FROM usuarios WHERE usuario=? LIMIT 1",d.getOrDefault("usuario",""));if(rows.isEmpty())return error("Usuario o contraseña incorrectos",HttpStatus.UNAUTHORIZED);var u=new HashMap<>(rows.get(0));if(((Number)u.get("activo")).intValue()!=1||!verify(String.valueOf(d.getOrDefault("password","")),String.valueOf(u.get("password"))))return error("Usuario o contraseña incorrectos",HttpStatus.UNAUTHORIZED);u.remove("password");u.put("token",u.get("id")+"|"+u.get("rol"));return ResponseEntity.ok(Map.of("user",u));}
 @PostMapping("/register") ResponseEntity<?> register(@RequestBody Map<String,Object>d){String dob=String.valueOf(d.getOrDefault("fecha_nacimiento","2000-01-01"));int age=Period.between(LocalDate.parse(dob),LocalDate.now()).getYears();if(age<18||d.get("nombre")==null||d.get("apellido")==null||d.get("ci")==null||d.get("usuario")==null||String.valueOf(d.getOrDefault("password","")).length()<8||!Boolean.TRUE.equals(d.get("terminos")))return error("Datos inválidos o edad menor a 18",HttpStatus.UNPROCESSABLE_ENTITY);if(!db.queryForList("SELECT id FROM usuarios WHERE usuario=? OR ci=?",d.get("usuario"),d.get("ci")).isEmpty())return error("Usuario o CI ya registrado",HttpStatus.CONFLICT);db.update("INSERT INTO usuarios(nombre,apellido,ci,fecha_nacimiento,edad,usuario,password,rol,acepta_terminos,activo) VALUES(?,?,?,?,?,?,?,'cliente',1,1)",d.get("nombre"),d.get("apellido"),d.get("ci"),dob,age,d.get("usuario"),makePass(String.valueOf(d.get("password"))));return ResponseEntity.status(201).body(Map.of("message","Cuenta creada"));}
 @GetMapping("/clientes") ResponseEntity<?> clientes(@RequestHeader(value="Authorization",defaultValue="")String t){var e=role(t,"administrador");if(e!=null)return e;return ResponseEntity.ok(db.queryForList("SELECT id,nombre,apellido,ci,fecha_nacimiento,edad,usuario,rol,cargo,activo,created_at FROM usuarios WHERE rol='cliente' ORDER BY id DESC"));}
 @DeleteMapping("/clientes/{id}") ResponseEntity<?> delCliente(@RequestHeader(value="Authorization",defaultValue="")String t,@PathVariable int id){var e=role(t,"administrador");if(e!=null)return e;try{int a=db.update("DELETE FROM usuarios WHERE id=? AND rol='cliente'",id);if(a==0)return error("Cliente no encontrado o no es cliente",HttpStatus.NOT_FOUND);return ResponseEntity.ok(Map.of("message","Cliente eliminado"));}catch(Exception ex){try{db.update("UPDATE usuarios SET activo=0 WHERE id=? AND rol='cliente'",id);return ResponseEntity.ok(Map.of("message","El cliente tiene ventas asociadas; fue desactivado en su lugar"));}catch(Exception ex2){return error("No se pudo eliminar el cliente: "+ex.getMessage(),HttpStatus.CONFLICT);}}}
 @PostMapping("/clientes") ResponseEntity<?> addCliente(@RequestHeader(value="Authorization",defaultValue="")String t,@RequestBody Map<String,Object>d){var e=role(t,"administrador");if(e!=null)return e;String dob=String.valueOf(d.getOrDefault("fecha_nacimiento","2000-01-01"));int age=Period.between(LocalDate.parse(dob),LocalDate.now()).getYears();db.update("INSERT INTO usuarios(nombre,apellido,ci,fecha_nacimiento,edad,usuario,password,rol,acepta_terminos,activo) VALUES(?,?,?,?,?,?,?,'cliente',1,1)",d.get("nombre"),d.get("apellido"),d.get("ci"),dob,age,d.get("usuario"),makePass(String.valueOf(d.getOrDefault("password","Cliente123"))));return ResponseEntity.status(201).body(Map.of("message","Cliente creado"));}
 @PutMapping("/clientes/{id}") ResponseEntity<?> updCliente(@RequestHeader(value="Authorization",defaultValue="")String t,@PathVariable int id,@RequestBody Map<String,Object>d){var e=role(t,"administrador");if(e!=null)return e;String dob=String.valueOf(d.getOrDefault("fecha_nacimiento","2000-01-01"));int age=Period.between(LocalDate.parse(dob),LocalDate.now()).getYears();db.update("UPDATE usuarios SET nombre=?,apellido=?,ci=?,fecha_nacimiento=?,edad=?,usuario=?,activo=? WHERE id=? AND rol='cliente'",d.get("nombre"),d.get("apellido"),d.get("ci"),dob,age,d.get("usuario"),((Boolean)d.getOrDefault("activo",true))?1:0,id);return ResponseEntity.ok(Map.of("message","Cliente actualizado"));}
 @GetMapping("/productos-publicos") List<Map<String,Object>> publicProducts(){return db.queryForList("SELECT * FROM productos WHERE activo=1 AND stock>0 ORDER BY nombre");}
 @GetMapping("/productos") ResponseEntity<?> products(@RequestHeader(value="Authorization",defaultValue="")String t){var e=role(t,"administrador","cajero");if(e!=null)return e;return ResponseEntity.ok(db.queryForList("SELECT * FROM productos ORDER BY nombre"));}
 @PostMapping("/productos") ResponseEntity<?> addProduct(@RequestHeader(value="Authorization",defaultValue="")String t,@RequestBody Map<String,Object>d){var e=role(t,"administrador","cajero");if(e!=null)return e;db.update("INSERT INTO productos(nombre,descripcion,precio,stock,activo) VALUES(?,?,?,?,?)",d.get("nombre"),d.getOrDefault("descripcion",""),d.getOrDefault("precio",0),d.getOrDefault("stock",0),((Boolean)d.getOrDefault("activo",true))?1:0);return ResponseEntity.status(201).body(Map.of("message","Producto creado"));}
 @PutMapping("/productos/{id}") ResponseEntity<?> updProduct(@RequestHeader(value="Authorization",defaultValue="")String t,@PathVariable int id,@RequestBody Map<String,Object>d){var e=role(t,"administrador","cajero");if(e!=null)return e;db.update("UPDATE productos SET nombre=?,descripcion=?,precio=?,stock=?,activo=? WHERE id=?",d.get("nombre"),d.getOrDefault("descripcion",""),d.getOrDefault("precio",0),d.getOrDefault("stock",0),((Boolean)d.getOrDefault("activo",true))?1:0,id);return ResponseEntity.ok(Map.of("message","Producto actualizado"));}
 @DeleteMapping("/productos/{id}") ResponseEntity<?> delProduct(@RequestHeader(value="Authorization",defaultValue="")String t,@PathVariable int id){var e=role(t,"administrador","cajero");if(e!=null)return e;try{db.update("DELETE FROM productos WHERE id=?",id);return ResponseEntity.ok(Map.of("message","Producto eliminado"));}catch(Exception ex){db.update("UPDATE productos SET activo=0 WHERE id=?",id);return ResponseEntity.ok(Map.of("message","Producto desactivado"));}}
 @GetMapping("/ventas") ResponseEntity<?> sales(@RequestHeader(value="Authorization",defaultValue="")String t){var e=role(t,"administrador","cajero","cliente");if(e!=null)return e;return ResponseEntity.ok(db.queryForList("SELECT v.id,v.usuario_id,v.total,v.estado,v.repartidor_id,v.created_at,u.nombre,u.apellido FROM ventas v LEFT JOIN usuarios u ON u.id=v.usuario_id ORDER BY v.id DESC"));}
 @PostMapping("/ventas") @Transactional ResponseEntity<?> sale(@RequestHeader(value="Authorization",defaultValue="")String t,@RequestBody Map<String,Object>d){var e=role(t,"administrador","cajero","cliente");if(e!=null)return e;var u=user(t);List<Map<String,Object>> items=(List<Map<String,Object>>)d.getOrDefault("items",List.of());if(items.isEmpty())return error("Agrega al menos un producto",HttpStatus.UNPROCESSABLE_ENTITY);double total=0;List<Map<String,Object>> rows=new ArrayList<>();for(var it:items){int pid=((Number)it.get("producto_id")).intValue(),qty=((Number)it.get("cantidad")).intValue();var rs=db.queryForList("SELECT * FROM productos WHERE id=? AND activo=1 FOR UPDATE",pid);if(rs.isEmpty())return error("Producto no encontrado",HttpStatus.UNPROCESSABLE_ENTITY);var p=rs.get(0);int stock=((Number)p.get("stock")).intValue();if(qty<1||stock<qty)return error("Stock insuficiente",HttpStatus.UNPROCESSABLE_ENTITY);rows.add(Map.of("id",pid,"q",qty,"price",((Number)p.get("precio")).doubleValue()));total+=((Number)p.get("precio")).doubleValue()*qty;}Integer cliente=d.get("cliente_id") instanceof Number?((Number)d.get("cliente_id")).intValue():(Integer)u.get("id");boolean esCajero="cajero".equals(u.get("rol"));String dirEntrega=d.get("direccion_entrega")==null?null:String.valueOf(d.get("direccion_entrega"));db.update("INSERT INTO ventas(usuario_id,cajero_id,tipo_venta,total,monto_cobrado,estado,estado_pago,direccion_entrega) VALUES(?,?,?,?,?,?,?,?)",cliente,esCajero?u.get("id"):null,esCajero?"mostrador":"delivery",total,esCajero?total:0,esCajero?"pagada":"pendiente",esCajero?"pagado":"pendiente",dirEntrega);Integer vid=db.queryForObject("SELECT LAST_INSERT_ID()",Integer.class);for(var r:rows){db.update("INSERT INTO detalle_venta(venta_id,producto_id,cantidad,precio_unitario) VALUES(?,?,?,?)",vid,r.get("id"),r.get("q"),r.get("price"));db.update("UPDATE productos SET stock=stock-? WHERE id=?",r.get("q"),r.get("id"));}return ResponseEntity.status(201).body(Map.of("message","Venta registrada","id",vid,"total",total));}
 @GetMapping("/entregas") ResponseEntity<?> deliveries(@RequestHeader(value="Authorization",defaultValue="")String t){var e=role(t,"repartidor");if(e!=null)return e;return ResponseEntity.ok(db.queryForList("SELECT v.id,v.total,v.estado,u.nombre,u.apellido FROM ventas v LEFT JOIN usuarios u ON u.id=v.usuario_id WHERE v.estado IN ('pendiente','en_camino') ORDER BY v.id"));}
 @PutMapping("/entregas/{id}") @Transactional ResponseEntity<?> deliver(@RequestHeader(value="Authorization",defaultValue="")String t,@PathVariable int id,@RequestBody(required=false) Map<String,Object> d){var e=role(t,"repartidor");if(e!=null)return e;var u=user(t);String accion=d==null?"entregado":String.valueOf(d.getOrDefault("accion","entregado"));String obs=d==null?null:(d.get("observacion")==null?null:String.valueOf(d.get("observacion")));
  if("no_entregado".equals(accion)){db.update("UPDATE ventas SET estado='no_entregado',estado_pago='anulado',monto_cobrado=0,repartidor_id=?,fecha_entrega=NOW(),observacion_entrega=? WHERE id=? AND estado IN ('pendiente','en_camino')",u.get("id"),obs==null?"El cliente no recibio el pedido":obs,id);
   for(var r:db.queryForList("SELECT producto_id,cantidad FROM detalle_venta WHERE venta_id=?",id)){db.update("UPDATE productos SET stock=stock+? WHERE id=?",r.get("cantidad"),r.get("producto_id"));}
   return ResponseEntity.ok(Map.of("message","Pedido marcado como NO entregado. Los productos volvieron al inventario."));}
  db.update("UPDATE ventas SET estado='entregada',estado_pago='pagado',monto_cobrado=total,repartidor_id=?,fecha_entrega=NOW(),observacion_entrega=? WHERE id=? AND estado IN ('pendiente','en_camino')",u.get("id"),obs==null?"Entrega conforme":obs,id);return ResponseEntity.ok(Map.of("message","Producto entregado. Monto registrado correctamente."));}
}
